	/*CRIANDO TABELA COM FOREIGN KEY*/
ALTER TABLE NOTAS ADD CONSTRAINT FK_CLIENTES 
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE NOTAS ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);