	/*CRIANDO TABELA COM FOREIGN KEY*/
   -- Foreign key são as informações que são idênticas em duas tabelas--
   
ALTER TABLE NOTAS ADD CONSTRAINT FK_CLIENTES 
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE NOTAS ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);