	/*TRANSICTION FAZ ALTERAÇÕES SEM ALTERAR OS DADOS*/
START TRANSACTION;

SELECT * FROM VENDEDORES;

UPDATE VENDEDORES SET COMISSAO = COMISSAO * 1.15;

ROLLBACK; /*ROLLBACK FUNÇÃO PARA NÃO SALVAR AS ALTERAÇÕES FEITAS*/

COMMIT; /*SALVA AS ALTERAÇÕES FEITAS*/
