	/*PREPARAÇÃO PARA TRIGGERS*/

CREATE TABLE TAB_FATURAMENTO
(DATA_VENDA DATE NULL, TOTAL_VENDA FLOAT);

SELECT * FROM TAB_FATURAMENTO;
SELECT * FROM NOTAS;
SELECT * FROM ITENS_NOTAS;

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('0100', '2019-05-08', '1471156710', '235', 0.100);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('0100', '1000889', 100, 10);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('0100', '1002334', 100, 10);

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('0101', '2019-05-08', '1471156710', '235', 0.100);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('0101', '1000889', 100, 10);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('0101', '1002334', 100, 10);

INSERT INTO TAB_FATURAMENTO
SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDAS FROM 
NOTAS A INNER JOIN ITENS_NOTAS B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA;

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('0103', '2019-05-08', '1471156710', '235', 0.100);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('0103', '1000889', 100, 10);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('0103', '1002334', 100, 10);

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('0104', '2019-05-08', '1471156710', '235', 0.100);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('0104', '1000889', 100, 10);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('0104', '1002334', 100, 10);
DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDAS FROM 
NOTAS A INNER JOIN ITENS_NOTAS B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA;

	/* COMANDO MANUAL PARA ATUALIZAÇÃO DA TABELA*/
INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('0105', '2019-05-08', '1471156710', '235', 0.100);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('0105', '1000889', 100, 10);
INSERT INTO ITENS_NOTAS (NUMERO, CODIGO_PRODUTO, QUANTIDADE, PRECO)
VALUES ('0105', '1002334', 100, 10);
DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDAS FROM 
NOTAS A INNER JOIN ITENS_NOTAS B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA; /* SEMPRE QUE HOUVER O ESTE SELECT UTILIZAR O GROUP BY*/

	/*CRIANDO TRIGGERS*/
DELETE FROM ITENS_NOTAS;
DELETE FROM NOTAS;
DELETE FROM TAB_FATURAMENTO;
SELECT * FROM ITENS_NOTAS;
SELECT * FROM NOTAS;
SELECT * FROM TAB_FATURAMENTO;

/* UTILIZADO PARA DELIMITAR O INICIO E O FIM DO COMANDO TRIGGER*/
DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_INSERT AFTER INSERT ON ITENS_NOTAS
FOR EACH ROW BEGIN
  DELETE FROM TAB_FATURAMENTO;
  INSERT INTO TAB_FATURAMENTO
  SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDAS FROM 
  NOTAS A INNER JOIN ITENS_NOTAS B
  ON A.NUMERO = B.NUMERO
  GROUP BY A.DATA_VENDA;
  END//
  
	/*EXERCICIO*/
SELECT CPF, IDADE, DATA_NASCIMENTO, timestampdiff(YEAR, DATA_NASCIMENTO, NOW()) AS ANOS FROM
CLIENTES;

DELIMITER //
CREATE TRIGGER TG_CLIENTES_IDADE_INSERT BEFORE INSERT ON CLIENTES
FOR EACH ROW
BEGIN
SET NEW.IDADE = timestampdiff(YEAR, NEW.DATA_NASCIMENTO, NOW());
END//


